import Link from "next/link";
import { Brain } from "lucide-react";

import { Button } from "@/components/ui/button";

export function HeroSection() {
  return (
    <section className="relative overflow-hidden py-20 md:py-32">
      <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-background" />
      <div className="container relative z-10">
        <div className="grid gap-12 md:grid-cols-2 md:gap-16">
          <div className="flex flex-col justify-center space-y-6">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                Test Your Knowledge with AI-Powered Quizzes
              </h1>
              <p className="text-lg text-muted-foreground md:text-xl">
                Challenge yourself with personalized quizzes generated by our
                advanced AI. Learn, compete, and have fun!
              </p>
            </div>
            <div className="flex flex-col gap-3 sm:flex-row">
              <Button size="lg" asChild>
                <Link href="#featured-quizzes">Start a Quiz</Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link href="/about">Learn More</Link>
              </Button>
            </div>
          </div>
          <div className="flex items-center justify-center">
            <div className="relative aspect-square w-full max-w-md rounded-full bg-gradient-to-br from-primary/20 via-primary/10 to-background p-4">
              <div className="absolute inset-0 flex items-center justify-center">
                <Brain className="h-32 w-32 text-primary md:h-48 md:w-48" />
              </div>
              <div className="absolute -right-4 -top-4 flex h-24 w-24 items-center justify-center rounded-full bg-primary text-primary-foreground md:-right-8 md:-top-8 md:h-32 md:w-32">
                <div className="text-center">
                  <div className="text-xl font-bold md:text-3xl">AI</div>
                  <div className="text-xs md:text-sm">Powered</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
